name: Sync PR to Bitbucket

on:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  sync-to-bitbucket:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history to avoid shallow clone error

      - name: Push to Bitbucket
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote add bitbucket https://${{ secrets.BITBUCKET_USERNAME }}:${{ secrets.BITBUCKET_APP_PASSWORD }}@bitbucket.org/${{ secrets.BITBUCKET_REPO }}.git
          git push --force bitbucket HEAD:refs/heads/${{ github.event.pull_request.head.ref }}

  notify:
    needs: [sync-to-bitbucket]
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - uses: lacherogwu/failed-jobs-discord-notification-action@v1
        with:
          discord_webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          needs_json: ${{ toJSON(needs) }}
